name: Auto Commit Changes

on:
  create:
    branches:
      - '*'

permissions:
  packages: read
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'Alice[bot]'
          git config --global user.email 'Alice[bot]@wonderland.com'

      - name: Make changes to packing_list.md
        run: |
          echo "[] Alice's personal toothbrush" >> packing_list.md
          git add packing_list.md
          git commit -m "Auto-update packing_list.md with new item"

      - name: Push changes to main branch
        run: |
          git fetch origin
          git checkout main
          git merge --no-ff ${{ github.ref }}
          git push origin main
